---
# tasks file for capo

- name: Ensure the ~/.config/openstack directory exists
  ansible.builtin.file:
    path: "~/.config/openstack"
    state: directory
    mode: '0700'

- name: Create and populate the clouds.yaml file
  ansible.builtin.copy:
    dest: "~/.config/openstack/clouds.yaml"
    content: |
      clouds:
        {{ cloud_name_key }}:
          auth:
            auth_url: "{{ auth_url }}"
            application_credential_id: "{{ application_credential_id }}"
            application_credential_secret: "{{ application_credential_secret }}"
          region_name: "{{ region_name }}"
          interface: "{{ interface }}"
          identity_api_version: {{ identity_api_version }}
          auth_type: "{{ auth_type }}"
    mode: '0600'

- name: Ensure ~/.bashrc exists
  ansible.builtin.file:
    path: "~/.bashrc"
    state: touch

- name: Ensure OpenStack environment variables section is present in ~/.bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    line: '# OpenStack environment variables'
    create: yes
    insertafter: EOF
    state: present

- name: Ensure OpenStack DNS Nameservers is set in ~/.bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    line: 'export OPENSTACK_DNS_NAMESERVERS={{ openstack_dns_nameservers }}'
    create: yes
    insertafter: '# OpenStack environment variables'
    state: present

- name: Ensure OpenStack Failure Domain is set in ~/.bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    line: 'export OPENSTACK_FAILURE_DOMAIN={{ openstack_failure_domain }}'
    create: yes
    insertafter: '# OpenStack environment variables'
    state: present

- name: Ensure OpenStack Control Plane Machine Flavor is set in ~/.bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    line: 'export OPENSTACK_CONTROL_PLANE_MACHINE_FLAVOR={{ openstack_control_plane_machine_flavor }}'
    create: yes
    insertafter: '# OpenStack environment variables'
    state: present

- name: Ensure OpenStack Node Machine Flavor is set in ~/.bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    line: 'export OPENSTACK_NODE_MACHINE_FLAVOR={{ openstack_node_machine_flavor }}'
    create: yes
    insertafter: '# OpenStack environment variables'
    state: present

- name: Ensure OpenStack Image Name is set in ~/.bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    line: 'export OPENSTACK_IMAGE_NAME={{ openstack_image_name }}'
    create: yes
    insertafter: '# OpenStack environment variables'
    state: present

- name: Ensure OpenStack SSH Key Name is set in ~/.bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    line: 'export OPENSTACK_SSH_KEY_NAME={{ openstack_ssh_key_name }}'
    create: yes
    insertafter: '# OpenStack environment variables'
    state: present

- name: Ensure OpenStack External Network ID is set in ~/.bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    line: 'export OPENSTACK_EXTERNAL_NETWORK_ID={{ openstack_external_network_id }}'
    create: yes
    insertafter: '# OpenStack environment variables'
    state: present

- name: Source the ~/.bashrc file to apply changes 
  ansible.builtin.shell:
    cmd: "source ~/.bashrc"
    executable: /bin/bash

- name: Download clusterctl binary
  become: yes
  become_method: sudo
  get_url:
    url: https://github.com/kubernetes-sigs/cluster-api/releases/download/{{ clusterctl_version }}/clusterctl-linux-amd64
    dest: /tmp/clusterctl-linux-amd64
    mode: '0755'

- name: Move clusterctl binary to /usr/local/bin
  become: yes
  become_method: sudo
  command: mv /tmp/clusterctl-linux-amd64 /usr/local/bin/clusterctl


- name: Download and install kustomize via script
  shell: |
    curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
    mv kustomize /usr/local/bin/kustomize
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"

- name: Ensure git is installed
  package:
    name: git
    state: present

- name: Clone the repository
  git:
    repo: "{{ clusterctl_git_resources }}"
    dest: "/tmp/clusterapi"
    version: main
    force: yes

# - name: Set ORC version
#   set_fact:
#     orc_version: "v2.1.0"

- name: Install OpenStack Resource Controller
  become: yes
  become_method: sudo
  shell: |
    kubectl apply -f "https://github.com/k-orc/openstack-resource-controller/releases/download/{{ orc_version }}/install.yaml"
  args:
    warn: false


- name: Initialize management cluster
  become: yes
  become_method: sudo
  shell: clusterctl init --infrastructure openstack


# - name: Install cert-manager if not already installed
#   command: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.17.1/cert-manager.yaml
#   args:
#     creates: /tmp/cert-manager-installed
#   register: cert_manager_apply

# - name: Mark cert-manager as installed
#   file:
#     path: /tmp/cert-manager-installed
#     state: touch
#   when: cert_manager_apply.changed

# - name: Wait for cert-manager webhook to be ready
#   shell: |
#     kubectl wait --namespace cert-manager \
#       --for=condition=Available deployment/cert-manager-webhook \
#       --timeout=120s
#   register: webhook_ready
#   retries: 5
#   delay: 10
#   until: webhook_ready.rc == 0


# - name: Apply CAPO kustomize resources in config/default
#   shell: |
#     kustomize build /tmp/clusterapi/config/default | kubectl apply -f -
#   args:
#     executable: /bin/bash