---
# vars file for capa

service_names:
  - "docker"
  - "kubelet"

clusterctl_version: v1.10.1
orc_version: "v2.1.0"

clusterctl_git_resources: https://github.com/kubernetes-sigs/cluster-api-provider-openstack.git

cloud_name_key: "openstack"
auth_url: "http://192.168.24.13:5000/v3/"
application_credential_id: "bf180f7ffc0d45ffb59e858dccdf1501"
application_credential_secret: "mgmt"
region_name: "RegionOne"
interface: "public"
identity_api_version: 3
auth_type: "v3applicationcredential"

openstack_dns_nameservers: "8.8.8.8"
openstack_failure_domain: "compute"
openstack_control_plane_machine_flavor: "nephio"
openstack_node_machine_flavor: "nephio"
openstack_image_name: "Ubuntu22-CAPI"
openstack_ssh_key_name: "workflow-prj"
openstack_external_network_id: "88e1ee39-f1e8-4b1b-b77a-a819a366da2b"


# dJxdsVt46YGJ191U2Zx_9yrQAf4BWpZ3DWLEpeSdGHAGwvUkKA5cKPLXcA1tY0f_nB4kC9qUxA1tvjK-wLBjwg