---
# vars file for capa

service_names:
  - "docker"
  - "kubelet"

clusterctl_version: v1.10.1

cloud_name_key: "openstack"
auth_url: "http://192.168.24.13:5000/v3/"
application_credential_id: "ca8224ace8fb41afa5483ef5100e6e2d"
application_credential_secret: "52wkHGEnV_Y5CnGTLpTe5YOx5LUQi2qWHPcMqianFrRRpQo5DHUHw03nPJv4ZnCWozfQhkwS2HlOyKWf_4lVZA"
region_name: "RegionOne"
interface: "public"
identity_api_version: 3
auth_type: "v3applicationcredential"

openstack_dns_nameservers: "8.8.8.8"
openstack_failure_domain: "compute"
openstack_control_plane_machine_flavor: "m1.large"
openstack_node_machine_flavor: "m1.xlarge"
openstack_image_name: "Ubuntu22-CAPI"
openstack_ssh_key_name: "karmada-kt-24"
openstack_external_network_id: "88e1ee39-f1e8-4b1b-b77a-a819a366da2b"


# dJxdsVt46YGJ191U2Zx_9yrQAf4BWpZ3DWLEpeSdGHAGwvUkKA5cKPLXcA1tY0f_nB4kC9qUxA1tvjK-wLBjwg